=== nhjschulz/flashcontainer/src/flashcontainer/pargen_1.0.xsd
<!--
BSD 3-Clause License

Copyright (c) 2022, Haju Schulz (haju.schulz@online.de)

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 -->

 <!-- XSD grammer for pargen XML input -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://nhjschulz.github.io/1.0/pargen"
    xmlns="http://nhjschulz.github.io/1.0/pargen"
    xmlns:pargen="http://nhjschulz.github.io/1.0/pargen"
    elementFormDefault="qualified">

    <xs:element name="pargen">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element name="container">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="blocks">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                        <xs:element name="block" type="pargen:block"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="at" type="pargen:uint64" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="block">
        <xs:sequence>
            <xs:element name="comment" type="pargen:textonly" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="header" type="pargen:header" minOccurs="0" maxOccurs="1"></xs:element>
            <xs:element name="data" type="pargen:data"></xs:element>
        </xs:sequence>
        <xs:attribute name="offset" type="pargen:address" use="required" />
        <xs:attribute name="name" type="pargen:identifier" use="required" />
        <xs:attribute name="length" type="pargen:uint32" use="required" />
        <xs:attribute name="endianness" type="pargen:endianness" use="optional" default="LE" />
        <xs:attribute name="align" type="pargen:align" use="optional" default="1" />
        <xs:attribute name="fill" type="pargen:uint8" use="optional" default="0x00" />
    </xs:complexType>

    <xs:complexType name="header">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="pargen:uint16" use="required" />
                <xs:attribute name="major" type="pargen:uint16" use="required" />
                <xs:attribute name="minor" type="pargen:uint16" use="required" />
                <xs:attribute name="version" type="pargen:uint16" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="data">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="param" type="pargen:param"></xs:element>
            <xs:element name="crc" type="pargen:crc"></xs:element>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="param_base">
        <xs:sequence>
            <xs:element name="comment" type="pargen:textonly" minOccurs="0" maxOccurs="1"></xs:element>
        </xs:sequence>
        <xs:attribute name="offset" type="pargen:address" use="required" />
        <xs:attribute name="name" type="pargen:identifier" use="required" />
        <xs:attribute name="type" type="pargen:type" use="required" />
        <xs:attribute name="align" type="pargen:align" use="optional" default="1" />
    </xs:complexType>

    <xs:complexType name="param">
        <xs:complexContent>
            <xs:extension base="pargen:param_base">
                <xs:sequence>
                    <xs:element name="value" type="pargen:textonly" minOccurs="1" maxOccurs="1"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="crc">
        <xs:complexContent>
            <xs:extension base="pargen:param_base">
                <xs:sequence>
                    <xs:element name="memory" type="pargen:memory" minOccurs="1" maxOccurs="1"></xs:element>
                    <xs:element name="config" type="pargen:crccfg" minOccurs="0" maxOccurs="1"></xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="crccfg">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="polynomial" type="uint32" use="optional" default="0x04C11DB7" />
                <xs:attribute name="init" type="uint32" use="optional" default="0xFFFFFFFF" />
                <xs:attribute name="rev_in" type="xs:boolean" use="optional" default="true" />
                <xs:attribute name="rev_out" type="xs:boolean" use="optional" default="true" />
                <xs:attribute name="final_xor" type="xs:boolean" use="optional" default="true" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="memory">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="from" type="pargen:address" default="0x0000" />
                <xs:attribute name="to" type="pargen:address" default="." />
                <xs:attribute name="access" type="pargen:access" use="optional" default="8" />
                <xs:attribute name="swap" type="xs:boolean" use="optional" default="false" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="utf8">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="length" type="uint32" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="uint8">
        <xs:restriction base="xs:string">
            <xs:pattern value="0x[0-9a-fA-F]{1,2}|0|[1-2][0-9]{0,2}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="uint16">
        <xs:restriction base="xs:string">
            <xs:pattern value="0x[0-9a-fA-F]{1,4}|0|[1-9][0-9]{0,5}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="uint32">
        <xs:restriction base="xs:string">
            <xs:pattern value="0x[0-9a-fA-F]{1,8}|0|[1-9][0-9]{1,9}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="uint64">
        <xs:restriction base="xs:string">
            <xs:pattern value="0x[0-9a-fA-F]{1,16}|0|[1-9][0-9]{1,20}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="address">
        <xs:restriction base="xs:string">
            <xs:pattern value="0x[0-9a-fA-F]{1,16}|0|[1-9][0-9]{1,20}|\." />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idstr32">
        <xs:restriction base="xs:string">
            <xs:maxLength value="32"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="identifier">
        <xs:restriction base="xs:string"></xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="uint32" />
            <xs:enumeration value="uint8" />
            <xs:enumeration value="uint16" />
            <xs:enumeration value="uint64" />
            <xs:enumeration value="int8" />
            <xs:enumeration value="int16" />
            <xs:enumeration value="int32" />
            <xs:enumeration value="int64" />
            <xs:enumeration value="float32" />
            <xs:enumeration value="float64" />
            <xs:enumeration value="utf8" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="endianness">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LE" />
            <xs:enumeration value="BE" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="align">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1" />
            <xs:enumeration value="2" />
            <xs:enumeration value="4" />
            <xs:enumeration value="8" />
            <xs:enumeration value="16" />
            <xs:enumeration value="32" />
            <xs:enumeration value="64" />
            <xs:enumeration value="128" />
            <xs:enumeration value="256" />
            <xs:enumeration value="512" />
            <xs:enumeration value="1024" />
            <xs:enumeration value="2048" />
            <xs:enumeration value="4096" />
            <xs:enumeration value="8192" />
            <xs:enumeration value="16384" />
       </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="access">
        <xs:restriction base="xs:string">
            <xs:enumeration value="8" />
            <xs:enumeration value="16" />
            <xs:enumeration value="32" />
            <xs:enumeration value="64" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="textonly">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== nhjschulz/flashcontainer/examples/arduino_struct_test/param/weird.xml
<?xml version="1.0" encoding="utf-8"?>
<pd:pargen xmlns:pd="http://nhjschulz.github.io/1.0/pargen"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://nhjschulz.github.io/1.0/pargen ./../../src/flashcontainer/pargen_1.0.xsd" >
    <pd:struct name="SimpleS" fill="parent">
        <pd:comment>This struct is super simple</pd:comment>
        <pd:fields>
            <pd:field name="int1" type="uint8" />
            <pd:field name="int2" type="uint8" />
            <pd:crc name="smallcrc" type="uint8">
                <pd:memory from="0x0000" to="."/>
                <pd:config polynomial="0x55" init="0xFF"></pd:config>
            </pd:crc>
        </pd:fields>
    </pd:struct>
    <pd:struct name="ComplexS" fill="parent">
        <pd:comment>This struct will feature padding and arrays</pd:comment>
        <pd:fields>
            <pd:field name="int1" type="uint8" />
            <pd:padding size="4"/>
            <pd:field name="int2" type="uint64">
                <pd:comment>I will need so much space</pd:comment>
            </pd:field>
            <pd:padding size="2" />
            <pd:arrayfield name="intarray" type="uint16" size="4"/>
        </pd:fields>
    </pd:struct>
    <pd:container name="CodeFlash" at="0x80000000">
        <pd:blocks>
            <pd:block offset="0x00000000" name="paraBlkQm" length="0x100" endianness="LE" fill="0x55">
                <pd:comment>This block is used for non-safety related parameters only.</pd:comment>
                <pd:header id="0xFFFF" major="1" minor="0" version="0"></pd:header>
                <pd:data>
                    <pd:param offset="0x10" name="crcTestInput" type="uint8">
                        <pd:comment>see https://www.boost.org/doc/libs/1_79_0/libs/crc/test/crc_test2.cpp</pd:comment>
                        <pd:value>[0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39]</pd:value>
                    </pd:param>
                    <pd:crc offset="." name="crcTestResult" type="uint32">
                        <pd:comment>expected: CBF43926</pd:comment>
                        <pd:memory from="0x10" to="."></pd:memory>
                    </pd:crc>
                    <pd:param offset="0x20" name="tag" type="int16">
                            <pd:comment>Integer array example</pd:comment>
                            <pd:value>[-4, -3, -2, -1, 0, 1, 2, 3, 4]</pd:value>
                        </pd:param>
                    <pd:crc offset="0xfc" name="crc" type="uint32">
                        <pd:comment>block crc32 (IEEE802.3)</pd:comment>
                        <pd:memory from="0x0000" to="."/>
                        <pd:config polynomial="0x04C11DB7" init="0xFFFFFFFF" rev_in="true" rev_out="true" final_xor="true"></pd:config>
                    </pd:crc>
                </pd:data>
            </pd:block>

            <pd:block name="paraBlkSafety" offset="." length="0x200" endianness="LE" align="512" fill="0xab">
                <pd:comment>This block is used for any-safety related parameters.</pd:comment>
                <pd:header id="0x0D00" major="1" minor="0" version="0"/>
                <pd:data>
                    <pd:param offset="0x10" name="array" type="float32" align="4">
                        <pd:value>[0.111,-2.1,3.2,4.5,5.4,6.5]</pd:value>
                    </pd:param>
                    <pd:param offset="0x100" name="hello" type="utf8">
                        <pd:value>"Hello world!"</pd:value>
                    </pd:param>
                    <pd:param offset="." name="val" type="uint16" align="2">
                        <pd:value>0x1604</pd:value>
                    </pd:param>
                    <pd:param offset="." name="birthday" type="float32">
                        <pd:value>0.160469</pd:value>
                    </pd:param>
                    <pd:param offset="." name="negativePi" type="float32">
                        <pd:value>-3.141</pd:value>
                    </pd:param>
                    <pd:crc offset="0x1fc" name="crc2" type="uint32">
                         <pd:comment>block crc32 (IEEE802.3)</pd:comment>
                         <pd:memory from="0x0000" to="."/>
                    </pd:crc>
                </pd:data>
            </pd:block>

            <pd:block offset="0x400" name="structTestBlock" length="0x200" endianness="LE" align="256" fill="0xFF">
                <pd:comment>This block contains parameters that use structs</pd:comment>
                <pd:header id="0x0E12" major="1" minor="0" version="0"/>
                <pd:data>
                    <pd:param offset="." name="simpy" type="complex" struct="SimpleS">
                        <pd:value>{ "int1": 3, "int2": 5}</pd:value>
                    </pd:param>
                    <pd:param offset="." name="biggy" type="complex" struct="ComplexS">
                        <pd:value>{"int1": 1, "int2": 9999999, "intarray": [1, 4, 16, 64]}</pd:value>
                    </pd:param>
                    <pd:param offset="0x10E" name="igetreadbyval" type="uint16">
                        <pd:value>0x3553</pd:value>
                    </pd:param>
                </pd:data>
            </pd:block>
        </pd:blocks>
    </pd:container>
</pd:pargen>

=== nhjschulz/flashcontainer/examples/arduino_struct_test/param/param.xml
<?xml version="1.0" encoding="utf-8"?>
<pd:pargen xmlns:pd="http://nhjschulz.github.io/1.0/pargen"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://nhjschulz.github.io/1.0/pargen http://nhjschulz.github.io/xsd/pargen_1.0.xsd" >
    <pd:container name="EEPROM" at="0x81000000">
        <pd:blocks>
            <pd:block offset="0x0000" name="par" length="0x400" fill="0xAA">
                <pd:comment>1Kb Example parameter block for displaying a flashable message with update delay</pd:comment>
                <pd:header id="0xEE" major="1" minor="0" version="1"></pd:header>
                <pd:data>
                    <pd:param offset="." name="par_UpdateDelay_ms" type="uint16">
                        <pd:comment>Interval time between dumping welcome message.</pd:comment>
                        <pd:value>2000</pd:value>
                    </pd:param>
                    <pd:param offset="." name="par_WelcomeMsg_str" type="utf8">
                        <pd:comment>Message to display in endless loop.</pd:comment>
                        <pd:value>"This message is defined as a Pargen parameter!\r\n"</pd:value>
                    </pd:param>
                    <pd:crc offset="0x03fc" name="par_crc" type="uint32">
                        <pd:memory from="0x0000" to="."/>
                    </pd:crc>
                </pd:data>
            </pd:block>
        </pd:blocks>
    </pd:container>
</pd:pargen>
